import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

export default function JournalLayout({ children }) {
    return (
      <div>
        {children}
      </div>
    );
  }