import type { Metadata } from "next";
import { ReactNode } from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

interface DashboardLayoutProps {
  children: ReactNode;
  }

export default function DashboardLayout({ children }: DashboardLayoutProps) {
    return (
      <div>
        {/* Your layout structure */}
        {children}
      </div>
    );
  }